- platform: yeelight
  devices:
    192.168.1.114:
      name: Corridor
      transition: 300
      model: color2
      save_on_change: True
- platform: yeelight
  devices:
    192.168.1.159:
      name: Living Room
      transition: 300
      model: color2
      save_on_change: True