homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 0
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

updater:

config:

hassio:

system_health:

tts:
  - platform: google
    language: 'it'
    base_url: https://xxxxxx.duckdns.org:8123

panel_iframe:
  ide:
    title: IDE
    icon: mdi:wrench
    url: http://192.168.1.XXX:8321
  esp:
    title: Esp Config
    icon: mdi:application
    url: http://192.168.1.XXX:6052
  tasmota:
    title: Tasmo Admin
    icon: mdi:application
    url: http://192.168.1.XXX:9541

http:
  base_url: !secret http_base_url
  ssl_profile: intermediate
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

logger:
  default: info

#device_tracker:
#  - platform: bluetooth_tracker
#    interval_seconds: 60
#    new_device_defaults:
#      track_new_devices: False

history:

logbook:

sun:

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    name: camera
    input: !secret camera_url

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_apy_key
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_bot_chat_id


input_text:
  wunderlist_groceries:
    name: Aggiungi a Lista Spesa

input_boolean:
  alarm_weekday:
    name: Sveglia
    initial: on
    icon: mdi:timer
 
input_number:
  alarm_hour:
    name: alarm_hour
    icon: mdi:clock-start
    initial: 7
    min: 0
    max: 24
    step: 1
  alarm_minute:
    name: alarm_minute
    icon: mdi:clock-start
    initial: 0
    min: 0
    max: 60
    step: 5
          
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
    name: Meteo

wunderlist:
  client_id: !secret wunderlist_client_id
  access_token: !secret wunderlist_access_token

climate:
  - platform: generic_thermostat
    name: air_conditioner_thermostat
    heater: switch.air_conditioner
    target_sensor: sensor.temperature
    ac_mode: true

fastdotcom:
  scan_interval:
    minutes: 180

recorder:
  purge_keep_days: 1

snips:

group: !include groups.yaml
alarm_control_panel: !include_dir_merge_list components/alarm_control_panel
sensor: !include_dir_merge_list components/sensors
switch: !include_dir_merge_list components/switches
light: !include_dir_merge_list components/lights

media_player: !include_dir_merge_list components/media_players
notify: !include_dir_merge_list components/notify

intent_script: !include intents/snips.yaml
scene: !include scenes.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml