- alias: Wall Switch Yeelight 1
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d000237bb73
      click_type: single
  action:
  - data:
      entity_id: light.living_room
    service: light.toggle

- alias: Button Yeelight 1
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201c19c
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201c19c
        click_type: hold
  action:
  - data:
      entity_id: light.living_room
    service: light.toggle