- alias: Cube Spotify - change Track
  trigger:
    event_data:
      action_type: flip90
      entity_id: binary_sensor.cube_158d000103a838
    event_type: xiaomi_aqara.cube_action
    platform: event
  action:
  #  service_template: '{% if trigger.event.data.action_value|float > 16 %} media_player.media_next_track  {%
  #    elif trigger.event.data.action_value|float < -16 %} media_player.media_previous_track
  #    {% endif %}'
  - service: media_player.media_next_track
    data:
      entity_id: media_player.spotify
- alias: Cube Spotify - play-pause
  trigger:
    event_data:
      action_type: tap_twice
      entity_id: binary_sensor.cube_158d000103a838
    event_type: xiaomi_aqara.cube_action
    platform: event
  action:
    service: media_player.media_play_pause
    data:
      entity_id: media_player.spotify

############### Button ################
- alias: Button - 
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201c19c
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201c19c
        click_type: hold
  action:
    service: media_player.media_play_pause
    data:
      entity_id: media_player.spotify