- alias: Telegram Turn On light 
  trigger:
  - event_data:
      command: /luce
    event_type: telegram_command
    platform: event
  - event_data:
      data: /luce
    event_type: telegram_callback
    platform: event
  condition: []
  action:
  - alias: ''
    data: {}
    service: switch.toggle
  - data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Azione Completata
    service: telegram_bot.answer_callback_query
- alias: Telegram help
  trigger:
    event_data:
      command: '/help'
    event_type: telegram_command
    platform: event
  action:
  - service: telegram_bot.send_message
    data:
      message: 'Cosa vuoi fare:'
      inline_keyboard:
      - Accendi Luce:/luce, Task 2:/command2
      - Task 3:/command3, Task 4:/command4