- platform: command_line
  command: curl http://192.168.1.104/PRESENTATION/HTML/TOP/INDEX.HTML | awk '/Ink_K.PNG/ {print $4}' | awk -F "'" '{printf "%.0f\n",  $2/50*100;}'
  name: Epson WF-2510 Black
  unit_of_measurement: '%'
  scan_interval: 1800
- platform: command_line
  command: curl http://192.168.1.104/PRESENTATION/HTML/TOP/INDEX.HTML | awk '/Ink_Y.PNG/ {print $4}' | awk -F "'" '{printf "%.0f\n",  $2/50*100;}'
  name: Epson WF-2510 Yellow
  unit_of_measurement: '%'
  scan_interval: 1800
- platform: command_line
  command: curl http://192.168.1.104/PRESENTATION/HTML/TOP/INDEX.HTML | awk '/Ink_M.PNG/ {print $4}' | awk -F "'" '{printf "%.0f\n",  $2/50*100;}'
  name: Epson WF-2510 Magenta
  unit_of_measurement: '%'
  scan_interval: 1800
- platform: command_line
  command: curl http://192.168.1.104/PRESENTATION/HTML/TOP/INDEX.HTML | awk '/Ink_C.PNG/ {print $4}' | awk -F "'" '{printf "%.0f\n",  $2/50*100;}'
  name: Epson WF-2510 Cyan
  unit_of_measurement: '%'
  scan_interval: 1800